

services:
  event-service:
    build:
      context: ./events-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-csu1c7a3esus73c5o8s0-a.oregon-postgres.render.com/event_schedule
      - SPRING_DATASOURCE_USERNAME=db_events_9wwt_user
      - SPRING_DATASOURCE_PASSWORD=sTA1L2gp0ko0EV4L6m87M8bIVpwFs9A7
      - RABBITMQ_HOST=jackal-01.rmq.cloudamqp.com
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  notification-service:
    build:
      context: ./notifications-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-csu1c7a3esus73c5o8s0-a.oregon-postgres.render.com/event_schedule
      - SPRING_DATASOURCE_USERNAME=db_events_9wwt_user
      - SPRING_DATASOURCE_PASSWORD=sTA1L2gp0ko0EV4L6m87M8bIVpwFs9A7
      - RABBITMQ_HOST=jackal-01.rmq.cloudamqp.com
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  api-gateway:
    build:
      context: ./cloud-gateway
    ports:
      - "8082:8082"
    depends_on:
      - event-service
      - notification-service
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  eureka:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  microservices-net:
    driver: bridge
